apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aws-list-products
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aws-list-products
            image: sivanamu/list-aws-products
          restartPolicy: OnFailure
